name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore Libmirobot/Libmirobot.sln
    - name: Build
      run: dotnet build Libmirobot/Libmirobot.sln --configuration Release --no-restore
    - name: Test
      run: dotnet test Libmirobot/Libmirobot.sln --no-restore --verbosity normal
    - name: Build NuGet package
      run: cd Libmirobot && dotnet pack -c Release -o out -p:NuspecFile=Libmirobot/Libmirobot.nuspec
    - name: Push generated package to GitHub registry
      run: dotnet nuget push ./Libmirobot/out/*.nupkg -k ${{ secrets.NUGETORG_PKG_PUSH_SECRET }} -s https://api.nuget.org/v3/index.json --skip-duplicate --no-symbols true
